Added headers templates
dalbitresb12/minigit pull request #8
Opened 2021-06-28 00:56 UTC by paredpiso

### Qué es lo que hace

Anadir los archivos plantillas de las clases para llenar con codigo

### Por qué es necesario

Para ayudar a la creacion de las clases.

2021-06-28 15:42 UTC, paredpiso reviewed
Added:
"repository.hpp" "stashmanager.hpp" "stash.hpp" "branch.hpp" "branchmanager.hpp"

2021-06-28 22:30 UTC, dalbitresb12 requested changes
Solo algunos cambios menores de estilo de código, todo lo demás está perfecto. 👍

2021-06-28 22:30 UTC, dalbitresb12 commented on src/branch.hpp
> +class Branch {
Entre la instrucción `#pragma once`, los _include_ y el inicio de la clase siempre es mejor poner una línea vacía. ¿Podrías hacer esto mismo en todos los archivos también?

```suggestion
#pragma once

#include <string>

class Branch {
```

2021-06-28 22:30 UTC, dalbitresb12 commented on src/branch.hpp
> +public:
Antes del `public` también se suele añadir una línea vacía.

2021-06-28 22:30 UTC, dalbitresb12 commented on src/branch.hpp
> +
Verifica que solo haya una línea vacía al final (en todos los archivos también).

2021-06-28 22:30 UTC, dalbitresb12 commented on src/branch.hpp
> +
También que no quede ninguna línea vacía antes de terminar la clase (en todos los archivos también).

2021-06-28 22:30 UTC, dalbitresb12 commented on src/minigit.hpp
> +class Minigit {
Aquí faltaría añadir las instrucciones de `using`:

```suggestion
#pragma once

#include <map>
#include <string>

using std::map;
using std::string;

class Minigit {
```

2021-06-28 22:30 UTC, dalbitresb12 commented on src/branchmanager.hpp
> +class BranchManager {
Aquí falta añadir los includes de las clases que usas.

```suggestion
#pragma once

#include "hashtable.hpp"
#include "branch.hpp"

class BranchManager {
```

2021-06-28 22:30 UTC, dalbitresb12 commented on src/branch.hpp
> +#include <string>
Aquí también usas HashTable, así que no te olvides de incluirlo: `#include "hashtable.hpp"`.

2021-06-28 22:30 UTC, dalbitresb12 commented on src/repository.hpp
> +class Repository {
No te olvides de los _includes_:

```suggestion
#pragma once

#include <string>
#include <vector>

#include "file.hpp"
#include "branch.hpp"
#include "branchmanager.hpp"
#include "stashmanager.hpp"

using std::string;
using std::vector;

class Repository {
```

2021-06-28 22:30 UTC, dalbitresb12 commented on src/repository.hpp
> +  Stashmanager* stash();
Te faltó la _M_ como mayúscula. :)

```suggestion
  StashManager* stash();
```

2021-06-28 22:30 UTC, dalbitresb12 commented on src/stash.hpp
> +#pragma once
Aquí también te faltaron los _includes_:

```cpp
#include <string>
#include <list>

#include "file.hpp"

using std::string;
using std::list;
```

2021-06-28 22:30 UTC, dalbitresb12 commented on src/stashmanager.hpp
> +#pragama once
```suggestion
#pragma once
```

2021-06-28 22:30 UTC, dalbitresb12 commented on src/stashmanager.hpp
> +#include "HashTables.hpp"
Esto faltaría actualizarse al nuevo nombre del archivo, que es `hashtable.hpp`. También falta el include de `stash.hpp`.

```suggestion
#include "hashtable.hpp"
#include "stash.hpp"
```

2021-06-28 22:30 UTC, dalbitresb12 commented on src/stashmanager.hpp
> +  Hashtable<Stash*> stashes;
Recuerda que la clase se llama `HashTable`.

```suggestion
  HashTable<Stash*> stashes;
```

2021-06-28 22:45 UTC, paredpiso commented on src/stashmanager.hpp
> +  Hashtable<Stash*> stashes;
La clase si se llama "HashTable" pero el nombre del hpp esta puesto como "HashTables.hpp" deberia cambiarle el nombre al header file o solo a esa linea 4 ?

2021-06-28 22:57 UTC, paredpiso commented on src/repository.hpp
> +  Stashmanager* stash();
Me di cuenta tambien que faltaba una "g" al final del string en la linea 20

2021-06-29 00:16 UTC, dalbitresb12 approved these changes
LGTM 👍

2021-06-29 00:16 UTC, merged